version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    groups:
      python-libs:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/services"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]
