version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-libs:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/services"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        versions: ["3.*"]
