# .sops.yaml — SOPS config for AWA-App
creation_rules:
  - path_regex: 'ops/secrets/.*\.enc\.(yaml|yml|json|env)$'
    # Fields commonly used for secrets in structured files
    encrypted_regex: '^(data|stringData|password|secret|token|apikey|api_key|client_secret|private_key)$'
    # IMPORTANT: replace with the real age public key (age1...):
    age: ['REPLACE_ME_WITH_AGE_RECIPIENT']
    mac_only_encrypted: true
