services:
  postgres:
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - awa-pgdata:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgres

  etl:
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgres

  repricer:
    build:
      context: ./services/repricer
    env_file:
      - .env.postgres
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  awa-pgdata:
