services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: awa
      POSTGRES_PASSWORD: awa
      POSTGRES_DB: awa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awa"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - awa-pgdata:/var/lib/postgresql/data

  api:
    depends_on: [postgres]
    environment:
      - DATABASE_URL=${DATABASE_URL}

  etl:
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgres

  repricer:
    build:
      context: ./services/repricer
    env_file:
      - .env.postgres
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  awa-pgdata:
