version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: UTC
      POSTGRES_INITDB_ARGS: --timezone=UTC
    ports:
      - "5432:5432"
    volumes:
      - awa-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    networks:
      - awa-net

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    networks:
      - awa-net

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      TZ: UTC
    env_file:
      - .env.postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8000/health"]
      start_period: 70s
      interval: 10s
      timeout: 3s
      retries: 6
    networks:
      - awa-net
    volumes:
      - awa-data:/data

  etl:
    build:
      context: .
      dockerfile: services/etl/Dockerfile
    env_file:
      - .env.postgres
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    healthcheck:
      test: ["CMD", "true"]
    networks:
      - awa-net
    volumes:
      - awa-data:/data

  web:
    build: ./webapp
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 24
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - awa-net

  repricer:
    build:
      context: ./services/repricer
    ports:
      - "8100:8100"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8100/health || exit 1"]
      interval: 10s
      retries: 5
    env_file:
      - .env.postgres
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - awa-net
    volumes:
      - awa-data:/data
  fees_h10:
    build: services/fees_h10
    command: ["celery", "-A", "services.fees_h10.worker", "beat", "-l", "info"]
    env_file: .env.postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - awa-net
  logistics_etl:
    build: services/logistics_etl
    env_file: .env.postgres
    command: ["python", "-m", "logistics_etl"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - awa-net

volumes:
  awa-pgdata:
  miniodata:
  awa-data:

networks:
  awa-net:
