services:
  postgres:
    image: postgres:15-alpine
    env_file: .env.postgres
    environment:
      TZ: UTC
      POSTGRES_INITDB_ARGS: --timezone=UTC
    command: ["postgres", "-c", "timezone=UTC"]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 10
  price_importer:
    build:
      context: .
      dockerfile: services/price_importer/Dockerfile
    volumes:
      - ./sample_prices:/data
    command: ["python", "-m", "price_importer.import", "/data/acme.xlsx", "--vendor", "ACME GmbH"]
    env_file: .env.postgres
    environment:
      TZ: UTC
    depends_on:
      postgres:
        condition: service_healthy
