version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    env_file: .env.postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${PG_USER}']
      interval: 5s
      retries: 10
  price_importer:
    build: services/price_importer
    volumes:
      - ./sample_prices:/data
    command: ["/app/entrypoint.sh", "/data/acme.xlsx", "--vendor", "ACME GmbH"]
    env_file: .env.postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8001/health"]
      interval: 10s
      retries: 3
