services:
  web:
    profiles: ["ci-skip"]
    ports: []
  repricer:
    profiles: ["ci-skip"]
    ports: []
  logistics_etl:
    profiles: ["ci-skip"]
  db:
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8000/ready"]
      start_period: 30s
      interval: 5s
      timeout: 2s
      retries: 30
    volumes: []
    environment:
      AUTO_CREATE_DB: "1"
