services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass # pragma: allowlist secret
      TZ: UTC
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      TZ: UTC
  web:
    build: ./web
    ports: ["3000:80"]
    depends_on: [api]
