services:
  postgres:
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: awa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - awa-pgdata:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:${PG_PASSWORD}@postgres:5432/awa

  etl:
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:${PG_PASSWORD}@postgres:5432/awa

  repricer:
    build:
      context: ./services/repricer
    env_file:
      - .env.postgres
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:${PG_PASSWORD}@postgres:5432/awa

volumes:
  awa-pgdata:
