services:
  web:
    profiles: ["ci-skip"]
    ports: []
  repricer:
    profiles: ["ci-skip"]
    ports: []
  logistics_etl:
    profiles: ["ci-skip"]
  api:
    healthcheck:
      start_period: 30s
      interval: 5s
      timeout: 3s
      retries: 20

