version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - .env.ci
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-awa}
