services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/api:${GITHUB_SHA}
    pull_policy: never  # Compose v2.23+: never contact registry
  postgres:
    image: postgres:15
    command: ["postgres","-c","timezone=UTC"]
