services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/api:${GITHUB_SHA}
    pull_policy: never            # requires Compose ≥2.23; otherwise omit and rely on --pull never
  postgres:
    image: postgres:15
    command: ["postgres", "-c", "timezone=UTC"]
