[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]
ignore = []

[tool.ruff.format]
skip-magic-trailing-comma = true
