[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
extend-select = ["B", "I", "C4", "T20"]
