[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
extend-select = ["I", "B", "UP", "ARG"]
ignore = [
  "ARG001",
  "ARG002",
  "ARG005",
  "B008",
  "B017",
  "B904",
  "UP006",
  "UP017",
  "UP035",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.coverage.run]
omit = [
  "*/__init__.py",
  "*/settings.py",
  "*/alembic/*",
  "*/migrations/*",
  "*/main.py",
  "*/sentry_config.py",
  "*/logging_config.py",
]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.vulture]
paths = ["services/api"]
exclude = ["tests/*"]
ignore_decorators = ["@router.get", "@router.post"]
ignore_names = ["__init__"]
