/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_upload__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Ingest */
        post: operations["submit_ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roi */
        get: operations["roi_roi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roi-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roi Review */
        get: operations["roi_review_roi_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roi-review/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_roi_review_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kpi */
        get: operations["kpi_stats_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/roi_by_vendor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roi By Vendor */
        get: operations["roi_by_vendor_stats_roi_by_vendor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns Stats */
        get: operations["returns_stats_stats_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/roi_trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roi Trend */
        get: operations["roi_trend_stats_roi_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score */
        post: operations["score_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sku/{asin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sku
         * @description Return title, ROI, fees, and recent price history for a SKU.
         */
        get: operations["get_sku_sku__asin__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sku/{asin}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Sku
         * @description Mark the SKU as approved if pending, returning the number of changes.
         */
        post: operations["approve_sku_sku__asin__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_ingest_ingest_post */
        Body_submit_ingest_ingest_post: {
            /** File */
            file?: string | null;
        };
        /** Body_upload_upload__post */
        Body_upload_upload__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PaginationMeta
         * @description Common pagination envelope returned by list endpoints.
         */
        PaginationMeta: {
            /**
             * Page
             * @description Current 1-based page number
             */
            page: number;
            /**
             * Page Size
             * @description Configured page size
             */
            page_size: number;
            /**
             * Total
             * @description Total number of rows that match the filters
             */
            total: number;
            /**
             * Total Pages
             * @description Total pages derived from the total and page size
             */
            total_pages: number;
        };
        /**
         * ReturnsStatsItem
         * @description Aggregated returns information for a single ASIN.
         */
        ReturnsStatsItem: {
            /** Asin */
            asin: string;
            /**
             * Qty
             * @description Total quantity returned for the ASIN
             */
            qty: number;
            /**
             * Refund Amount
             * @description Total refund amount issued for the ASIN
             */
            refund_amount: number;
        };
        /**
         * ReturnsStatsResponse
         * @description Response used by the /stats/returns endpoint.
         */
        ReturnsStatsResponse: {
            /** Items */
            items: components["schemas"]["ReturnsStatsItem"][];
            /** Total Returns */
            total_returns: number;
            pagination: components["schemas"]["PaginationMeta"];
            summary: components["schemas"]["ReturnsSummary"];
        };
        /**
         * ReturnsSummary
         * @description Aggregate metrics used by the returns table summary widgets.
         */
        ReturnsSummary: {
            /**
             * Total Asins
             * @description Total ASINs that matched the filters
             */
            total_asins: number;
            /**
             * Total Units
             * @description Total quantity of units returned for the filters
             */
            total_units: number;
            /**
             * Total Refund Amount
             * @description Total refund amount issued for the filters
             */
            total_refund_amount: number;
            /**
             * Avg Refund Per Unit
             * @description Average refund per returned unit
             */
            avg_refund_per_unit: number;
            /**
             * Top Asin
             * @description ASIN with the highest refund amount for the filters
             */
            top_asin?: string | null;
            /**
             * Top Refund Amount
             * @description Refund amount associated with the ASIN that ranked first
             */
            top_refund_amount?: number | null;
        };
        /**
         * RoiApprovalResponse
         * @description Result payload for ROI approval actions.
         */
        RoiApprovalResponse: {
            /**
             * Updated
             * @description Number of SKUs updated by the approval request
             */
            updated: number;
            /**
             * Approved Ids
             * @description Identifiers that were approved in this request
             */
            approved_ids?: string[];
        };
        /**
         * RoiByVendorItem
         * @description Aggregated ROI metrics for a single vendor.
         */
        RoiByVendorItem: {
            /**
             * Vendor
             * @description Vendor identifier or name as provided by the query
             */
            vendor?: string | null;
            /**
             * Roi Avg
             * @description Average ROI percentage for the vendor
             */
            roi_avg: number;
            /**
             * Items
             * @description Number of SKUs used for the vendor aggregate
             */
            items: number;
        };
        /**
         * RoiByVendorResponse
         * @description Response for the /stats/roi_by_vendor endpoint.
         */
        RoiByVendorResponse: {
            /** Items */
            items: components["schemas"]["RoiByVendorItem"][];
            /** Total Vendors */
            total_vendors: number;
        };
        /**
         * RoiListResponse
         * @description Paginated ROI response returned by /roi.
         */
        RoiListResponse: {
            /** Items */
            items: components["schemas"]["RoiRow"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * RoiRow
         * @description Single row returned by the ROI listings endpoint.
         */
        RoiRow: {
            /**
             * Asin
             * @description Amazon ASIN identifier
             */
            asin: string;
            /**
             * Title
             * @description Product title
             */
            title?: string | null;
            /**
             * Category
             * @description Product category as stored in products.category
             */
            category?: string | null;
            /**
             * Vendor Id
             * @description Identifier of the vendor supplying the SKU
             */
            vendor_id?: number | null;
            /**
             * Cost
             * @description Vendor cost in EUR
             */
            cost?: number | null;
            /**
             * Freight
             * @description Estimated freight cost per unit in EUR
             */
            freight?: number | null;
            /**
             * Fees
             * @description Aggregated FBA fees in EUR
             */
            fees?: number | null;
            /**
             * Roi Pct
             * @description Return on investment percentage for the SKU
             */
            roi_pct?: number | null;
        };
        /**
         * RoiTrendPoint
         * @description Monthly ROI trend point.
         */
        RoiTrendPoint: {
            /**
             * Month
             * @description Month (YYYY-MM-DD) extracted from ROI snapshots
             */
            month: string;
            /**
             * Roi Avg
             * @description Average ROI for the month
             */
            roi_avg: number;
            /**
             * Items
             * @description Number of SKUs that contributed to the month aggregate
             */
            items: number;
        };
        /**
         * RoiTrendResponse
         * @description Response for the /stats/roi_trend endpoint.
         */
        RoiTrendResponse: {
            /** Points */
            points: components["schemas"]["RoiTrendPoint"][];
        };
        /** ScoreItem */
        ScoreItem: {
            /** Asin */
            asin: string;
            /** Roi */
            roi?: number | null;
            /** Vendor */
            vendor?: string | null;
            /** Category */
            category?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ScoreRequest */
        ScoreRequest: {
            /**
             * Asins
             * @description List of ASINs
             */
            asins: string[];
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Items */
            items: components["schemas"]["ScoreItem"][];
        };
        /**
         * SkuApprovalResponse
         * @description Response describing the result of approving a SKU.
         */
        SkuApprovalResponse: {
            /**
             * Approved
             * @description Flag indicating the SKU was marked as approved
             */
            approved: boolean;
            /**
             * Changed
             * @description Number of rows changed by the approval operation
             */
            changed: number;
        };
        /**
         * SkuChartPoint
         * @description Single point in the SKU price history chart.
         */
        SkuChartPoint: {
            /**
             * Date
             * @description ISO8601 timestamp of the price capture
             */
            date: string;
            /**
             * Price
             * @description Observed Buy Box price at the capture time
             */
            price: number;
        };
        /**
         * SkuResponse
         * @description Detailed SKU response used by /sku/{asin}.
         */
        SkuResponse: {
            /**
             * Title
             * @description Product title from the catalog
             */
            title: string;
            /**
             * Roi
             * @description ROI percentage from the ROI view
             */
            roi: number;
            /**
             * Fees
             * @description Fees associated with the SKU
             */
            fees: number;
            /**
             * Chartdata
             * @description Historical price series for the SKU
             */
            chartData: components["schemas"]["SkuChartPoint"][];
        };
        /**
         * StatsKPI
         * @description Aggregate ROI KPIs displayed on the stats dashboard.
         */
        StatsKPI: {
            /**
             * Roi Avg
             * @description Average ROI percentage across the ROI view
             */
            roi_avg: number;
            /**
             * Products
             * @description Count of distinct ASINs considered in the KPI query
             */
            products: number;
            /**
             * Vendors
             * @description Count of vendors found in the ROI view
             */
            vendors: number;
        };
        /**
         * StatsKPIResponse
         * @description Wrapper response for KPI aggregates.
         */
        StatsKPIResponse: {
            kpi: components["schemas"]["StatsKPI"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_upload__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_upload__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ingest_ingest_post: {
        parameters: {
            query?: {
                uri?: string | null;
                report_type?: string | null;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roi_roi_get: {
        parameters: {
            query?: {
                roi_min?: number;
                vendor?: number | null;
                category?: string | null;
                page?: number;
                page_size?: number;
                sort?: "roi_pct_desc" | "roi_pct_asc" | "asin_asc" | "asin_desc" | "margin_desc" | "margin_asc" | "vendor_asc" | "vendor_desc";
                search?: string | null;
                observe_only?: boolean;
                roi_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoiListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roi_review_roi_review_get: {
        parameters: {
            query?: {
                roi_min?: number;
                vendor?: number | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_roi_review_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoiApprovalResponse"];
                };
            };
        };
    };
    kpi_stats_kpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsKPIResponse"];
                };
            };
        };
    };
    roi_by_vendor_stats_roi_by_vendor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoiByVendorResponse"];
                };
            };
        };
    };
    returns_stats_stats_returns_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                asin?: string | null;
                vendor?: string | null;
                group_by?: string;
                page?: number;
                page_size?: number;
                sort?: "refund_desc" | "refund_asc" | "qty_desc" | "qty_asc" | "asin_asc" | "asin_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roi_trend_stats_roi_trend_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoiTrendResponse"];
                };
            };
        };
    };
    score_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sku_sku__asin__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_sku_sku__asin__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
