name: ci-logs
on:
  workflow_run:
    workflows: ["CI", "compose-e2e", "test"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  collect-and-commit:
    # do nothing if this is our own logs workflow
    if: ${{ github.event.workflow_run.name != 'ci-logs' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || 'main' }}
          fetch-depth: 0

      - name: Determine target directory
        id: vars
        run: |
          WF_NAME="${{ github.event.workflow_run.name }}"
          echo "wf_dir=ci-logs/latest/${WF_NAME}" >> $GITHUB_OUTPUT

      - name: Prepare directories
        run: |
          set -Eeuo pipefail
          mkdir -p "${{ steps.vars.outputs.wf_dir }}"

      - name: Download artifacts from triggering workflow
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: "${{ steps.vars.outputs.wf_dir }}/artifacts"
        continue-on-error: true

      - name: Write minimal run summary if no artifacts
        run: |
          printf "Run ID: %s\nConclusion: %s\n" \
            "${{ github.event.workflow_run.id }}" \
            "${{ github.event.workflow_run.conclusion }}" \
            > "${{ steps.vars.outputs.wf_dir }}/run.txt"
        continue-on-error: true

      - name: Write index for this run
        run: |
          {
            echo "# Logs for workflow: ${{ github.event.workflow_run.name }}"
            echo ""
            echo "- Run: ${{ github.event.workflow_run.id }}"
            echo "- Conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "- Branch: ${{ github.event.workflow_run.head_branch }}"
            echo "- SHA: ${{ github.event.workflow_run.head_sha }}"
            echo ""
            echo "## Contents"
            find "${{ steps.vars.outputs.wf_dir }}" -type f | sed 's#^#- #'
          } > "${{ steps.vars.outputs.wf_dir }}/README.md"

      - name: Commit logs
        env:
          GH_USER_NAME: "ci-logs-bot"
          GH_USER_EMAIL: "ci-logs-bot@users.noreply.github.com"
        run: |
          set -Eeuo pipefail
          git config user.name  "$GH_USER_NAME"
          git config user.email "$GH_USER_EMAIL"
          BR="ci-logs/${{ github.run_id }}"
          git checkout -B "$BR"
          git add -A ci-logs/latest
          if git diff --cached --quiet; then
            echo "No log changes to commit."
            exit 0
          fi
          git commit -m "ci-logs: update logs for ${{ github.event.workflow_run.name }} run ${{ github.event.workflow_run.id }}"
          git push -f origin "$BR"

      - name: Open or update PR for logs
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci-logs/${{ github.run_id }}
          title: "ci-logs: update logs for ${{ github.event.workflow_run.name }} (run ${{ github.run_id }})"
          body: "Automated logs update from workflow_run `${{ github.event.workflow_run.name }}`."
          commit-message: "ci-logs: update"
          labels: ci-logs
          base: ${{ github.event.workflow_run.head_branch || 'main' }}
