name: ci-postgres

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENABLE_LIVE: "1"
      DATABASE_URL: postgresql+asyncpg://postgres:pass@postgres:5432/postgres
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r services/etl/requirements.txt
          pip install -r services/api/requirements.txt
          pip install -r services/repricer/requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest
      - name: Start services
        run: docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d --wait
      - run: docker compose logs postgres
      - run: pytest -q
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
