name: ci-postgres

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENABLE_LIVE: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r services/etl/requirements.txt
          pip install -r services/api/requirements.txt
          pip install -r services/repricer/requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest
      - name: Load env
        run: |
          cat .env.postgres >> $GITHUB_ENV
          echo "PG_PASSWORD=postgres" >> $GITHUB_ENV
      - name: Start services
        run: docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d --wait
      - run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.postgres.yml \
            logs postgres
      - name: Run tests
        run: pytest -q
