name: ci-postgres

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENABLE_LIVE: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r services/etl/requirements.txt
          pip install -r services/api/requirements.txt
          pip install -r services/repricer/requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest
      - name: Start services
        run: docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d --wait
      - run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.postgres.yml \
            logs postgres
      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql+psycopg://postgres:pass@localhost:5432/postgres" >> $GITHUB_ENV
      - name: Run tests
        run: |
          export $(cat .env.postgres | xargs)
          pytest -q
